"""Add indexes to key model fields

Revision ID: 4aa76aa16464
Revises: 9371fea54616
Create Date: 2025-06-12 04:22:17.984155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aa76aa16464'
down_revision = '9371fea54616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_last_name'), ['last_name'], unique=False)

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_therapist_id'), ['therapist_id'], unique=False)

    with op.batch_alter_table('therapist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_therapist_last_name'), ['last_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('therapist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_therapist_last_name'))

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_therapist_id'))
        batch_op.drop_index(batch_op.f('ix_session_status'))
        batch_op.drop_index(batch_op.f('ix_session_start_time'))
        batch_op.drop_index(batch_op.f('ix_session_patient_id'))

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_last_name'))

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_patient_id'))

    # ### end Alembic commands ###
